<?php

/**
 * Created by PhpStorm.
 * User: Saidmurod Saidkhonov
 * Date: 10/4/18
 * Time: 12:23
 */

use Illuminate\Database\Seeder;
use Faker\Factory;
use App\Position;
use App\RawParent;
use App\Raw;
use App\Firm;
use App\RawFirm;
use Illuminate\Support\Facades\DB;


class RawSeeder extends Seeder
{

    public function run(){
        $faker = Factory::create();
        Position::truncate();
        $sections = ['A', 'B', 'C', 'D'];
        foreach($sections as $section){
            foreach(range(1,4) as $raw){
                foreach(range(1,27) as $column){
                    Position::create([
                        'section'=>$section,
                        'raw'=>$raw,
                        'column'=>$column,
                    ]);
                }
            }
        }

        Firm::truncate();
        $firms = [
            'Стиралка',
            'Холодильник',
            'Экструдер',
            'Газ плита',
            'Пылeсос',
            'Лампа',
            'Водонагреватель',
            'Вытяжка',
            'Сушилка',
        ];
        $company_names = [
            'Allegro',
            'Magic Plastics',
            'Techno Continental',
            'Magic Plastics',
            'Allegro',
            'Magic Plastics',
            'Techno Continental',
            'Techno Continental',
            'Allegro',
        ];
        foreach($firms as $index => $firm){
            Firm::create([
                'name'=> $firm,
                'company_name' => $company_names[$index],
            ]);
        }
        $colors = [
            'натурал',
            'прозрачный',
            'коричневый',
            'белый',
            'серый',
            'красный',
            'зеленый',
            'синий',
            'черный',
            'светлосерый',
            'темносиний',
            'темносерый',
            'матовый',
            'металлик',
            'бордовый',
        ];
        DB::table('colors')->truncate();
        foreach($colors as $color){
            DB::table('colors')->insert([
                'name' => $color,
            ]);
        }

        $rawParents = [
            [ 'name' => 'ABS', 'ancestors' => '1,', 'parent_id' => null ],
            [ 'name' => 'HIPS', 'ancestors' => '2,', 'parent_id' => null],
            [ 'name' => 'GPPS', 'ancestors' => '3,', 'parent_id' => null],
            [ 'name' => 'POM', 'ancestors' => '4,', 'parent_id' => null],
            [ 'name' => 'PP', 'ancestors' => '5,', 'parent_id' => null],
            [ 'name' => 'PS', 'ancestors' => '6,', 'parent_id' => null],
            [ 'name' => 'PA', 'ancestors' => '7,', 'parent_id' => null],
            [ 'name' => 'PBT', 'ancestors' => '8,', 'parent_id' => null],
            [ 'name' => 'EVA', 'ancestors' => '9,', 'parent_id' => null],
            [ 'name' => 'PVC', 'ancestors' => '10,', 'parent_id' => null],
            [ 'name' => 'Cleaning compound', 'ancestors' => '11,', 'parent_id' => null],
            [ 'name' => 'Master batch', 'ancestors' => '12,', 'parent_id' => null],
            [ 'name' => 'Полиэтилен', 'ancestors' => '13,', 'parent_id' => null],
            [ 'name' => 'Термоэластамер', 'ancestors' => '14,', 'parent_id' => null],
            [ 'name' => 'Краситель', 'ancestors' => '15,', 'parent_id' => null],
            [ 'name' => 'Наполнитель', 'ancestors' => '16,', 'parent_id' => null],
            [ 'name' => 'Аксессуар', 'ancestors' => '17,', 'parent_id' => null],

            [ 'name' => 'ABS WHITE', 'ancestors' => '1,18,', 'parent_id' => 1],
            [ 'name' => 'ABS Natural', 'ancestors' => '1,19,', 'parent_id' => 1],
            [ 'name' => 'ABS TX0510', 'ancestors' => '1,20,', 'parent_id' => 1],
            [ 'name' => 'ABS TR558A', 'ancestors' => '1,21,', 'parent_id' => 1],
            [ 'name' => 'ABS Colored', 'ancestors' => '1,22,', 'parent_id' => 1],
            [ 'name' => 'ABS HG 0760 GP/W92151', 'ancestors' => '1,23,', 'parent_id' => 1],
            [ 'name' => 'ABS QU', 'ancestors' => '1,24,', 'parent_id' => 1],
            [ 'name' => 'ABS HF380', 'ancestors' => '1,25,', 'parent_id' => 1],
            [ 'name' => 'ABS XR40', 'ancestors' => '1,26,', 'parent_id' => 1],

            [ 'name' => 'PP X', 'ancestors' => '5,27,', 'parent_id' => 5],
            [ 'name' => 'PP Samsung', 'ancestors' => '5,28,', 'parent_id' => 5],
            [ 'name' => 'PP Автомат', 'ancestors' => '5,29,', 'parent_id' => 5],

            [ 'name' => 'PA 6', 'ancestors' => '7,30,', 'parent_id' => 7],
            [ 'name' => 'PA 66', 'ancestors' => '7,31,', 'parent_id' => 7],

            [ 'name' => 'PVC DM', 'ancestors' => '10,32,', 'parent_id' => 10],

            [ 'name' => 'Краситель ABS', 'ancestors' => '15,33,', 'parent_id' => 15],
            [ 'name' => 'Краситель HIPS', 'ancestors' => '15,34,', 'parent_id' => 15],
            [ 'name' => 'Краситель GPPS', 'ancestors' => '15,35,', 'parent_id' => 15],
            [ 'name' => 'Краситель PS', 'ancestors' => '15,36,', 'parent_id' => 15],
            [ 'name' => 'Краситель STEADY', 'ancestors' => '15,37,', 'parent_id' => 15]

        ];
        DB::table('raw_parents')->truncate();
        DB::table('raw_firm')->truncate();
        DB::table('raws')->truncate();
        DB::table('raw_parents')->insert($rawParents);

        $raws = [
            [ 'id' => 1, 'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 2,'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 3, 'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 4, 'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 5, 'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => 11, 'quantity' => 0],
            [ 'id' => 6, 'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => 10, 'quantity' => 0],
            [ 'id' => 7, 'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 8, 'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 9, 'name' => 'ABS', 'parent_raw_id' => '1', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 10, 'name' => 'ABS VF (530400100007)', 'parent_raw_id' => '1', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 11, 'name' => 'ABS LG HI121IH', 'parent_raw_id' => '1', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 12, 'name' => 'ABS LG HI121IH', 'parent_raw_id' => '1', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 13, 'name' => 'ABS LG HI121IH', 'parent_raw_id' => '1', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 14, 'name' => 'ABS LG HI121IH', 'parent_raw_id' => '1', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 15, 'name' => 'MABS', 'parent_raw_id' => '1', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 16, 'name' => 'MABS', 'parent_raw_id' => '1', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 17, 'name' => 'ABS SD-0150 W95629', 'parent_raw_id' => '1', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 18, 'name' => 'ABS GP-22', 'parent_raw_id' => '1', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 19, 'name' => 'ABS X0822', 'parent_raw_id' => '1', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 20, 'name' => 'ABS 775', 'parent_raw_id' => '1', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 21, 'name' => 'ABS RS670', 'parent_raw_id' => '1', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 22, 'name' => 'ABS Y1817C1', 'parent_raw_id' => '1', 'color_id' => 15, 'quantity' => 0],
            [ 'id' => 23, 'name' => 'ABS Z7705C1', 'parent_raw_id' => '1', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 24, 'name' => 'ABS HI121 B-03', 'parent_raw_id' => '1', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 25, 'name' => 'ABS HG0760 (K2637)', 'parent_raw_id' => '1', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 26, 'name' => 'ABS FB-100', 'parent_raw_id' => '1', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 27, 'name' => 'HIPS', 'parent_raw_id' => '2', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 28, 'name' => 'HIPS', 'parent_raw_id' => '2', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 29, 'name' => 'HIPS', 'parent_raw_id' => '2', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 30, 'name' => 'HIPS VF (530400100008)', 'parent_raw_id' => '1', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 31, 'name' => 'HIPS VF (530400100008)', 'parent_raw_id' => '1', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 32, 'name' => 'HIPS VF (530400100008)', 'parent_raw_id' => '1', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 33, 'name' => 'HIPS HI450NPG', 'parent_raw_id' => '2', 'color_id' => 1, 'quantity' => 0],
            [ 'id' => 34, 'name' => 'HIPS HI450CPG', 'parent_raw_id' => '2', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 35, 'name' => 'HIPS 5197', 'parent_raw_id' => '2', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 36, 'name' => 'HIPS 470', 'parent_raw_id' => '2', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 37, 'name' => 'HIPS 470', 'parent_raw_id' => '2', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 38, 'name' => 'HIPS HI450PG', 'parent_raw_id' => '2', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 39, 'name' => 'HIPS VE 1877 (100F)', 'parent_raw_id' => '2', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 40, 'name' => 'HIPS VF', 'parent_raw_id' => '2', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 41, 'name' => 'GPPS', 'parent_raw_id' => '3', 'color_id' => 2, 'quantity' => 0],
            [ 'id' => 42, 'name' => 'GPPS GP150 N K', 'parent_raw_id' => '3', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 43, 'name' => 'GPPS GP150 N I', 'parent_raw_id' => '3', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 44, 'name' => 'GPPS GP116', 'parent_raw_id' => '3', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 45, 'name' => 'GPPS P G-383M (Samsung)', 'parent_raw_id' => '3', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 46, 'name' => 'GPPS GP125 N', 'parent_raw_id' => '3', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 47, 'name' => 'POM F20-03', 'parent_raw_id' => '4', 'color_id' => 1, 'quantity' => 0],
            [ 'id' => 48, 'name' => 'POM DPO-02W', 'parent_raw_id' => '4', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 49, 'name' => 'PP', 'parent_raw_id' => '5', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 50, 'name' => 'PP', 'parent_raw_id' => '5', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 51, 'name' => 'PP', 'parent_raw_id' => '5', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 52, 'name' => 'PP', 'parent_raw_id' => '5', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 53, 'name' => 'PP', 'parent_raw_id' => '5', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 54, 'name' => 'PP', 'parent_raw_id' => '5', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 55, 'name' => 'PP J340', 'parent_raw_id' => '5', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 56, 'name' => 'PP J340', 'parent_raw_id' => '5', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 57, 'name' => 'PP J350', 'parent_raw_id' => '5', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 58, 'name' => 'PP J740', 'parent_raw_id' => '5', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 59, 'name' => 'PP 548 Eron', 'parent_raw_id' => '5', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 60, 'name' => 'PS', 'parent_raw_id' => '6', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 61, 'name' => 'Tissan PBT', 'parent_raw_id' => '8', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 62, 'name' => 'Tissan PBT', 'parent_raw_id' => '8', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 63, 'name' => 'PBT China', 'parent_raw_id' => '8', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 64, 'name' => 'PBT WT9207M', 'parent_raw_id' => '8', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 65, 'name' => 'EVA', 'parent_raw_id' => '9', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 66, 'name' => 'Пластикат FT-20', 'parent_raw_id' => '10', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 67, 'name' => 'Пластикат FT-20', 'parent_raw_id' => '10', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 68, 'name' => 'Пластикат FT-25', 'parent_raw_id' => '10', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 69, 'name' => 'Пластикат FT-26', 'parent_raw_id' => '10', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 70, 'name' => 'AsaClean T7711', 'parent_raw_id' => '11', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 71, 'name' => 'Полиэтилен Cleaning compound', 'parent_raw_id' => '11', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 72, 'name' => 'EVA Color Master batch', 'parent_raw_id' => '12', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 73, 'name' => 'Master batch for ABS Plastic', 'parent_raw_id' => '12', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 74, 'name' => 'TR 100 S3GT-G001', 'parent_raw_id' => '12', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 75, 'name' => 'Полиэтилен 1561', 'parent_raw_id' => '13', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 76, 'name' => 'Полиэтилен местный', 'parent_raw_id' => '13', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 77, 'name' => 'Термоэластамер (AP8175W-AB) China', 'parent_raw_id' => '14', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 78, 'name' => 'Наполнитель', 'parent_raw_id' => '16', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 79, 'name' => 'PP Юмшок', 'parent_raw_id' => '17', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 80, 'name' => 'PP Каттик', 'parent_raw_id' => '17', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 81, 'name' => 'Anti Roddent', 'parent_raw_id' => null, 'color_id' => null, 'quantity' => 0],
            [ 'id' => 82, 'name' => 'Additive', 'parent_raw_id' => null, 'color_id' => null, 'quantity' => 0],
            [ 'id' => 83, 'name' => 'CMB-IF 9A280', 'parent_raw_id' => null, 'color_id' => null, 'quantity' => 0],

            [ 'id' => 84, 'name' => 'ABS HI121 OB707', 'parent_raw_id' => '18', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 85, 'name' => 'ABS 50C Eron', 'parent_raw_id' => '18', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 86, 'name' => 'ABS HI121', 'parent_raw_id' => '19', 'color_id' => 1, 'quantity' => 0],
            [ 'id' => 87, 'name' => 'ABS 750 N SW', 'parent_raw_id' => '19', 'color_id' => 1, 'quantity' => 0],
            [ 'id' => 88, 'name' => 'ABS 50', 'parent_raw_id' => '19', 'color_id' => 1, 'quantity' => 0],
            [ 'id' => 89, 'name' => 'ABS TX0510 (701264)', 'parent_raw_id' => '20', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 90, 'name' => 'ABS TX0510 (50287)', 'parent_raw_id' => '20', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 91, 'name' => 'ABS TX0510 (701261)', 'parent_raw_id' => '20', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 92, 'name' => 'ABS TX0510 (701263)', 'parent_raw_id' => '20', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 93, 'name' => 'ABS TX0510 (80477)', 'parent_raw_id' => '20', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 94, 'name' => 'ABS TX0510 (F40011)', 'parent_raw_id' => '20', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 95, 'name' => 'ABS TX0510 (F40008)', 'parent_raw_id' => '20', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 96, 'name' => 'ABS TR558A (49185)', 'parent_raw_id' => '21', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 97, 'name' => 'ABS TR558A (8M684)', 'parent_raw_id' => '21', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 98, 'name' => 'ABS TR558A (58855)', 'parent_raw_id' => '21', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 99, 'name' => 'ABS TR558A (4A082)', 'parent_raw_id' => '21', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 100, 'name' => 'ABS TR558', 'parent_raw_id' => '21', 'color_id' => 2, 'quantity' => 0],
            [ 'id' => 101, 'name' => 'ABS TR558A (6B395)', 'parent_raw_id' => '21', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 102, 'name' => 'ABS TR558A', 'parent_raw_id' => '21', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 103, 'name' => 'ABS HF380 8P836-C', 'parent_raw_id' => '22', 'color_id' => 14, 'quantity' => 0],
            [ 'id' => 104, 'name' => 'ABS HF380 8P837-A', 'parent_raw_id' => '22', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 105, 'name' => 'ABS HF380 58841-B', 'parent_raw_id' => '22', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 106, 'name' => 'ABS HF380 49978-A', 'parent_raw_id' => '22', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 107, 'name' => 'ABS 121H-X0822', 'parent_raw_id' => '23', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 108, 'name' => 'ABS HG 0760 GP/W92151', 'parent_raw_id' => '23', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 109, 'name' => 'ABS HG 0760 GP/G71936', 'parent_raw_id' => '23', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 110, 'name' => 'ABS VE 0856 NP', 'parent_raw_id' => '23', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 111, 'name' => 'ABS FR500', 'parent_raw_id' => '23', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 112, 'name' => 'ABS (75)', 'parent_raw_id' => '24', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 113, 'name' => 'ABS QU-0191/W91527 (Samsung)', 'parent_raw_id' => '24', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 114, 'name' => 'ABS QU-0191/W91528', 'parent_raw_id' => '24', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 115, 'name' => 'ABS LG HF380 OB249', 'parent_raw_id' => '25', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 116, 'name' => 'ABS LG HF380 OB304', 'parent_raw_id' => '25', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 117, 'name' => 'ABS (Жаропрочный) XR404', 'parent_raw_id' => '26', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 118, 'name' => 'ABS (Жаропрочный)', 'parent_raw_id' => '26', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 119, 'name' => 'PP J360 Nukus', 'parent_raw_id' => '27', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 120, 'name' => 'PP TV30', 'parent_raw_id' => '27', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 121, 'name' => 'PP BJ 750 (Samsung)', 'parent_raw_id' => '28', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 122, 'name' => 'PP BJ 3204 China (Samsung)', 'parent_raw_id' => '28', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 123, 'name' => 'PP PC2305 NATS', 'parent_raw_id' => '29', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 124, 'name' => 'PP PC2305 W229', 'parent_raw_id' => '29', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 125, 'name' => 'PP MT43 HBL', 'parent_raw_id' => '29', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 126, 'name' => 'PP K8003', 'parent_raw_id' => '29', 'color_id' => null, 'quantity' => 0],
            [ 'id' => 127, 'name' => 'PA 6', 'parent_raw_id' => '30', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 128, 'name' => 'PA 6', 'parent_raw_id' => '30', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 129, 'name' => 'Tissan PA 66', 'parent_raw_id' => '31', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 130, 'name' => 'Tissan PA 66', 'parent_raw_id' => '31', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 131, 'name' => 'Tissan PA 66 GFR', 'parent_raw_id' => '31', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 132, 'name' => 'Пластикат FT-60', 'parent_raw_id' => '32', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 133, 'name' => 'Пластикат FT-65', 'parent_raw_id' => '32', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 134, 'name' => 'PVX', 'parent_raw_id' => '32', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 135, 'name' => 'Краситель ABS AP-WG-50', 'parent_raw_id' => '33', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 136, 'name' => 'Краситель ABS AP-WG-75', 'parent_raw_id' => '33', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 137, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 3, 'quantity' => 0],
            [ 'id' => 138, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 139, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 140, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 141, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 142, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 143, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 144, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 10, 'quantity' => 0],
            [ 'id' => 145, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 11, 'quantity' => 0],
            [ 'id' => 146, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 12, 'quantity' => 0],
            [ 'id' => 147, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 13, 'quantity' => 0],
            [ 'id' => 148, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 14, 'quantity' => 0],
            [ 'id' => 149, 'name' => 'Краситель ABS', 'parent_raw_id' => '33', 'color_id' => 15, 'quantity' => 0],
            [ 'id' => 150, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 3, 'quantity' => 0],
            [ 'id' => 151, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 152, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 153, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 154, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 155, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 156, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 157, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 10, 'quantity' => 0],
            [ 'id' => 158, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 11, 'quantity' => 0],
            [ 'id' => 159, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 12, 'quantity' => 0],
            [ 'id' => 160, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 13, 'quantity' => 0],
            [ 'id' => 161, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 14, 'quantity' => 0],
            [ 'id' => 162, 'name' => 'Краситель HIPS', 'parent_raw_id' => '34', 'color_id' => 15, 'quantity' => 0],
            [ 'id' => 163, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 3, 'quantity' => 0],
            [ 'id' => 164, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 165, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 166, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 167, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 168, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 169, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 170, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 10, 'quantity' => 0],
            [ 'id' => 171, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 11, 'quantity' => 0],
            [ 'id' => 172, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 12, 'quantity' => 0],
            [ 'id' => 173, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 13, 'quantity' => 0],
            [ 'id' => 174, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 14, 'quantity' => 0],
            [ 'id' => 175, 'name' => 'Краситель GPPS', 'parent_raw_id' => '35', 'color_id' => 15, 'quantity' => 0],
            [ 'id' => 176, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 3, 'quantity' => 0],
            [ 'id' => 177, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 178, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 179, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 180, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 181, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 182, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 183, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 10, 'quantity' => 0],
            [ 'id' => 184, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 11, 'quantity' => 0],
            [ 'id' => 185, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 12, 'quantity' => 0],
            [ 'id' => 186, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 13, 'quantity' => 0],
            [ 'id' => 187, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 14, 'quantity' => 0],
            [ 'id' => 188, 'name' => 'Краситель PS', 'parent_raw_id' => '36', 'color_id' => 15, 'quantity' => 0],
            [ 'id' => 189, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 3, 'quantity' => 0],
            [ 'id' => 190, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 191, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 192, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 193, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 194, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 195, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 196, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 10, 'quantity' => 0],
            [ 'id' => 197, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 11, 'quantity' => 0],
            [ 'id' => 198, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 12, 'quantity' => 0],
            [ 'id' => 199, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 13, 'quantity' => 0],
            [ 'id' => 200, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 14, 'quantity' => 0],
            [ 'id' => 201, 'name' => 'Краситель STEADY', 'parent_raw_id' => '37', 'color_id' => 15, 'quantity' => 0],
            [ 'id' => 202, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 3, 'quantity' => 0],
            [ 'id' => 203, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 4, 'quantity' => 0],
            [ 'id' => 204, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 5, 'quantity' => 0],
            [ 'id' => 205, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 6, 'quantity' => 0],
            [ 'id' => 206, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 7, 'quantity' => 0],
            [ 'id' => 207, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 8, 'quantity' => 0],
            [ 'id' => 208, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 9, 'quantity' => 0],
            [ 'id' => 209, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 10, 'quantity' => 0],
            [ 'id' => 210, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 11, 'quantity' => 0],
            [ 'id' => 211, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 12, 'quantity' => 0],
            [ 'id' => 212, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 13, 'quantity' => 0],
            [ 'id' => 213, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 14, 'quantity' => 0],
            [ 'id' => 214, 'name' => 'Краситель', 'parent_raw_id' => '15', 'color_id' => 15, 'quantity' => 0],
        ];
        DB::table('raws')->insert($raws);

        $rawFirm = [          
            [ 'firm_id' => 1, 'raw_id' => 26, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 39, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 48, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 57, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 58, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 59, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 73, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 74, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 76, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 77, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 78, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 83, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 84, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 85, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 86, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 89, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 90, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 91, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 92, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 93, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 96, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 97, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 98, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 99, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 100, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 101, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 103, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 104, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 105, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 106, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 107, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 108, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 109, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 110, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 111, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 119, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 123, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 124, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 125, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 126, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 189, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 190, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 191, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 192, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 193, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 194, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 195, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 196, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 197, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 198, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 199, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 200, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 201, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 202, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 203, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 204, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 205, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 206, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 207, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 208, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 209, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 210, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 211, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 212, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 213, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 214, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 33, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 34, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 42, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 43, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 44, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 45, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 47, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 48, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 58, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 70, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 75, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 77, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 79, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 80, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 84, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 85, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 86, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 87, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 88, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 96, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 102, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 103, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 104, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 105, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 106, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 112, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 115, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 116, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 119, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 120, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 121, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 122, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 135, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 136, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 143, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 153, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 154, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 155, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 168, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 181, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 186, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 189, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 190, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 191, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 192, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 193, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 194, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 195, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 196, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 197, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 198, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 199, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 200, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 201, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 202, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 203, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 204, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 205, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 206, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 207, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 208, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 209, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 210, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 211, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 212, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 213, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 214, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 21, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 36, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 38, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 46, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 55, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 65, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 66, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 67, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 68, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 69, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 71, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 72, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 76, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 81, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 82, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 112, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 113, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 132, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 133, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 134, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 202, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 203, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 204, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 205, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 206, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 207, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 208, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 209, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 210, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 211, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 212, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 213, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 214, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 61, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 62, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 117, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 118, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 127, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 128, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 129, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 130, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 131, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 22, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 23, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 24, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 25, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 87, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 202, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 203, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 204, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 205, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 206, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 207, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 208, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 209, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 210, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 211, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 212, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 213, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 214, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 60, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 63, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 64, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 66, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 202, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 203, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 204, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 205, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 206, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 207, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 208, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 209, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 210, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 211, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 212, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 213, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 214, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],

            [ 'firm_id' => 1, 'raw_id' => 2, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 11, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 12, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 13, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 14, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 15, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 16, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 19, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 49, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 51, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 52, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 53, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 54, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 90, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 91, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 92, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 93, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 94, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 95, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 96, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 97, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 108, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 111, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 123, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 1, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 3, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 4, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 5, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 7, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 8, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 18, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 27, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 28, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 29, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 41, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 48, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 49, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 50, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 51, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 60, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 63, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 64, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 76, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 77, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 115, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 202, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 10, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 20, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 21, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 30, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 32, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 36, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 37, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 56, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 65, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 66, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 67, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 76, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 113, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 114, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 61, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 62, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 117, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 118, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 129, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 130, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 2, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 8, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 25, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 60, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 63, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 66, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 202, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 203, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 204, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 205, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 206, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 207, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 208, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 209, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 210, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 211, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 212, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 213, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 6, 'raw_id' => 214, 'type' => 2, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],

            [ 'firm_id' => 1, 'raw_id' => 2, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 3, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 8, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 9, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 49, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 51, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 52, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 91, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 92, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 1, 'raw_id' => 96, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 2, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 3, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 6, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 7, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 8, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 17, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 27, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 41, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 49, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 50, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 51, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 2, 'raw_id' => 115, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 10, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 20, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 31, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 32, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 36, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 37, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 56, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 3, 'raw_id' => 113, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 61, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 62, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 129, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 4, 'raw_id' => 130, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 8, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 22, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 5, 'raw_id' => 23, 'type' => 0, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],

            [ 'firm_id' => 7, 'raw_id' => 115, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 7, 'raw_id' => 116, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 7, 'raw_id' => 96, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 7, 'raw_id' => 102, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 8, 'raw_id' => 117, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 8, 'raw_id' => 118, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],
            [ 'firm_id' => 9, 'raw_id' => 75, 'type' => 1, 'position_id' => 1, 'quantity' => 0, 'valid_quantity' => 0],

        ];
        DB::table('raw_firm')->insert($rawFirm);
    }
}